name: main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Graphviz
        run: |
          sudo apt install graphviz

      - name: Install SvgBob
        run: |
          sudo cargo install svgbob_cli

      - name: Setup Node Package Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup packages
        run: npm ci --prefer-offline --no-audit
        env:
          HUSKY_SKIP_INSTALL: 1

      - name: Lint
        run: npm run lint

      - name: Build
        if: github.ref == 'refs/heads/master'
        run: npm run build
        env:
          GATSBY_TELEMETRY_DISABLED: 1

      - name: Upload
        if: github.ref == 'refs/heads/master'
        uses: Color-Of-Code/FTP-Deploy-Action@2.1.1
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          PORT: ${{ secrets.FTP_PORT }}
          LOCAL_DIR: public
          REMOTE_DIR: httpdocs
          METHOD: ftp
          ARGS: -v --delete --parallel=20
